name: ci
permissions:
  contents: write
on:
  push:
    branches:
      - main
  schedule:
    # ✅ 修改这里：只在周日到周四运行（0,1,2,3,4）
    - cron: "1 1 * * 0,1,2,3,4"  # UTC 01:01，仅周日～周四
jobs:
  autogreen:
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v4
      - name: Auto green
        env:
          TOKEN: ${{ secrets.GITHUB_TOKEN }}
          REPO: ${{ github.repository }}
          USER_EMAIL: "139669368+AcideFluorhydrique@users.noreply.github.com"
          USER_NAME: "AcideFluorhydrique"
        run: |
          git config --local user.email "${USER_EMAIL}"
          git config --local user.name "${USER_NAME}"
          git remote set-url origin https://x-access-token:${TOKEN}@github.com/${REPO}.git
          git pull --rebase
          git commit --allow-empty -m "Auto green commit"
          git push
